#!/bin/bash
recipient=”misswyne14@gmail.com”
recipient="a.itofe@msn.com"
subject=”Addiction”
echo message=”I sincerely welcome you to my heart”
echo "data" | mail -s "$subj" mail@mail

echo "every since i met you it has been nothing short of joy and fulfilment for me"
echo "you might not be perfect and i do not need a perfect man"
echo "you are just right for me only if you could be more romantic"
echo "you have treated me with love and respect"
echo "you are just interested in my growth which is the reason i fell in-love with you"
echo "I hope i make you happy cox i dont want to ever lose you"
echo " This is my true confession"
